---
title: "Polyp Risk Score results"
author: Mia Nahom
date: 2025-2-4
format: 
  html:
     df-print: paged
     embed-resources: true
---

## Load libraries
```{r}
#| output: false
library("DESeq2")
library("apeglm")
library("pheatmap")
library("tidyverse")
library("ggrepel")
library("ashr")
library("goseq")
library("biomaRt")
library("ggplot2")
library("clusterProfiler")
library("enrichplot")
library("ggupset")
library("data.table")
```

## Read in distal and proximal objects and set working directory

```{r}
#setwd(dir="../PolypRisk/")
directory <- "../counts/"
list.files(directory)

#Load Distal Table
DistalTable <- readRDS("../QC_meta/DistalTable.rds")
DistalTable<- DistalTable[DistalTable$fileName != "WS31-5_S58.counts", ]
DistalTable$risk <- factor(DistalTable$risk)
DistalTable
ProximalTable <- readRDS("../QC_meta/ProximalTable.rds")
ProximalTable<- ProximalTable[ProximalTable$fileName != "WS31-3_S57.counts", ]
ProximalTable$risk <- factor(ProximalTable$risk)
ProximalTable
```
## Create DESeq2 Object
```{r}
distal_ddsHTSeq <- DESeqDataSetFromHTSeqCount(
  sampleTable = DistalTable, 
  directory = directory, 
  design = ~ risk
)
proximal_ddsHTSeq <- DESeqDataSetFromHTSeqCount(
  sampleTable = ProximalTable, 
  directory = directory, 
  design = ~ risk
)
```
## Distal Analysis
### Filter out low expression genes
```{r}
# sum counts for each gene across samples
sumcounts <- rowSums(counts(distal_ddsHTSeq))
# take the log
logsumcounts <- log(sumcounts,base=10)
# plot a histogram of the log scaled counts
hist(logsumcounts,breaks=100)
# get genes with summed counts greater than 50
keep <- sumcounts > 50
distal_ddsHTSeq <- distal_ddsHTSeq[keep,]
```

### Set factors
```{r}
levels <- c("0","1","2")
distal_ddsHTSeq$risk <- factor(distal_ddsHTSeq$risk, levels = levels)
distal_ddsHTSeq$risk
```
### Get results
```{r}
distal_dds <- DESeq(distal_ddsHTSeq)
resultsNames(distal_dds)
```

### Extract Results
#### res1: 2 vs 0
#### res2: 1 vs 0
#### res3: 2 vs 1



```{r}
res1_dist <-results(distal_dds, name="risk_2_vs_0")
res2_dist <-results(distal_dds, name="risk_1_vs_0")
res3_dist <-results(distal_dds, contrast=list(c("risk_2_vs_0"),c("risk_1_vs_0")))
```
### Summary of results
```{r}
summary(res1_dist)
summary(res2_dist)
summary(res3_dist)
```

## Proximal Analysis
### Filter out low expression genes
```{r}
# sum counts for each gene across samples
sumcounts <- rowSums(counts(proximal_ddsHTSeq))
# take the log
logsumcounts <- log(sumcounts,base=10)
# plot a histogram of the log scaled counts
hist(logsumcounts,breaks=100)
# get genes with summed counts greater than 50
keep <- sumcounts > 50
proximal_ddsHTSeq <- proximal_ddsHTSeq[keep,]
```
### Set factors
```{r}
levels <- c("0","1","2")
proximal_ddsHTSeq$risk <- factor(proximal_ddsHTSeq$risk, levels = levels)
proximal_ddsHTSeq$risk
```
### Get results
```{r}
proximal_dds <- DESeq(proximal_ddsHTSeq)
resultsNames(proximal_dds)
```


### Extract Results
#### res1: 2 vs 0
#### res2: 1 vs 0
#### res3: 2 vs 1

```{r}
res1_prox <-results(proximal_dds, name="risk_2_vs_0")
res2_prox <-results(proximal_dds, name="risk_1_vs_0")
res3_prox <-results(proximal_dds, contrast=list(c("risk_2_vs_0"),c("risk_1_vs_0")))
```
### Summary of results
```{r}
summary(res1_prox)
summary(res2_prox)
summary(res3_prox)
```
